Feat/instruct
weavel-ai/Ape pull request #16
Opened 2024-09-06 17:18 UTC by shamuiscoding

@engineerA314 Need fix evaluation (to be able to return recall and precision) before merging

2024-09-07 22:15 UTC, engineerA314 commented
still debugging for `MIPROInstruct`

2024-09-07 22:17 UTC, engineerA314 commented on ape/proposer/instruct_by_score.py
> +                evaluation_result=str(evaluation_result),
what value should be sent to LLM as `evaluation_result`?
`List[EvaluationResult]`, or some part of it, or final score(float), or everything, or analysis of intermediate values?
@shamuiscoding

2024-09-11 04:18 UTC, aschung01 requested changes

2024-09-11 04:18 UTC, aschung01 commented on ape/ape_prompts/gen-instruction-with-eval.prompt
> +> Do not use backticks except for the CDATA section.
Let's remove this

2024-09-11 04:18 UTC, aschung01 commented on ape/proposer/instruct_by_score.py
> +class InstructByScore(Proposer):
Rename this to `EvaluationDrivenProposer`?

2024-09-11 23:22 UTC, aschung01 approved these changes

2024-09-11 23:23 UTC, merged